- id: doi:10.1038/s41467-019-11514-0
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/2019-08-07-dCas9-MCDDA-miCube.png
  tags:
    - Protein-DNA interactions
    - CRISPR-Cas
    - sptPALM
    - Software
    - Microbiology
    
- id: doi:10.1063/1.5005899
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/2017-12-22-phasor1.png
  tags:
    - SMLM
    - Software

- id: doi:10.1002/aocs.12035
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/2018-02-22-Raman-MFC.png
  tags:
    - Raman microscopy
    - Food structure

- id: doi:10.1021/acs.langmuir.8b03349
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/2019-01-14-Recrystall_MFC.png
  tags:
    - Raman microscopy
    - Food structure

- id: doi:10.1088/1478-3975/ab0162
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/2019-03-07-sptPALMlactis.png
  tags:
    - Protein-DNA interactions
    - CRISPR-Cas
    - sptPALM
    - Microbiology

- id: doi:10.1016/j.molcel.2019.10.021
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/2020-01-02-CascadeBrouns.png
  tags:
    - Protein-DNA interactions
    - CRISPR-Cas
    - sptPALM
    - Microbiology

- id: doi:10.1021/acs.langmuir.0c00393
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/Kcarrageenan_Langmuir.png
  tags:
    - Food structure
    - sptPALM

- id: doi:10.1016/j.ymeth.2020.07.010
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/phasor2_2021.png
  tags:
    - SMLM
    - Software

- id: doi:10.3389/fbinf.2021.817254
  image: https://raw.githubusercontent.com/kjamartens/MartensWebPage/main/_data/PublicationImages/codeTutorial_2021.png
  tags:
    - SMLM
    - sptPALM
    - Software
    - Tutorial


